pages/urls.py
from django.urls import path

from . import views

app_name = 'pages'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('about-us/', views.about_page, name='about_us'),
    path('residential/', views.residential_page, name='residential'),
    path('financing/', views.finance_page, name='financing'),
    path('services/', views.services_page, name='services'),
]

receives/urls.py
from . import views
from django.urls import path

app_name = 'receives'

urlpatterns = [
    # path('contact-us/',views.ContactUsPage.as_view(),name='contact_us_page'),
    # path('contact-us/send', views.contact_us, name='contact_us'),
    path('contact-us/', views.ContactUsView.as_view(), name='contact_us'),
    path('success/', views.success, name='contact_us_success'),
    path('submit-request/', views.MainRequestView.as_view(), name='request'),
]

service/urls.py
from . import views
from django.urls import path

app_name = 'service'

urlpatterns = [
    path('heating', views.heating_view, name='heating'),
    path('cooling/', views.cooling_view, name='cooling'),
    path('post/<int:post_id>/', views.post_view, name='post'),
]

wanaturalgas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls', namespace='pages')),
    path('', include('receives.urls', namespace='receives')),
    path('', include('service.urls', namespace='service')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler500 = handler500

templates/base/back_button.html
<div class="ggo float-left">
    <button class="forrmm" style="padding: 5px 10px;" type="button" onclick="history.back()"><i class="fas fa-long-arrow-alt-left fa-2x"></i></button>
</div>

templates/base/css.html
{% load static %}

<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">
<link rel="stylesheet" href="{% static 'css/all.min.css' %}">
<link rel="stylesheet" href="{% static 'css/slick.css' %}">
<link rel="stylesheet" href="{% static 'css/slick-theme.css' %}">
<link rel="stylesheet" href="{% static 'css/master.css' %}">

templates/base/footer.html
{% load static %}

    <!-- Start Footer -->
    <footer>
        <div class="container">
          <div class="row">
            <div class="col-lg-4 wow bounceIn" data-wow-duration="1s" data-wow-delay=".5s" data-wow-offset="300"><img class="sevnty" src="{% static 'img/white.png' %}" alt="">
              <p>Washington Natural Gas Heating & Air Conditioning 2208</p>
              <p>158th St SE</p>
              <p class="marg-bt">Mill Creek WA 98012</p>
              <div class="phon"><i class="fas fa-phone-volume"> </i><span> (425) 355-3331</span></div>
              <div class="phon"><i class="fas fa-phone-volume"> </i><span> (425) 355-3331</span></div>
              <div class="phon"><i class="fas fa-phone-volume"> </i><span> (425) 355-3331</span></div>
              <div class="phon"><i class="fas fa-phone-volume"> </i><span> (425) 355-3331</span></div>
              <div class="clearfix"></div>
              <p class="marg-tp"> Business License WASHING913LD</p>
            </div>
            <div class="col-lg-8">
              <div class="row">
                <div class="col-md-6 wow bounceIn" data-wow-duration="1s" data-wow-delay="1s" data-wow-offset="300">
                  <h2>Financing Available</h2><img src="{% static 'img/credit-cards.png' %}" alt="">
                </div>
                <div class="col-md-6 wow bounceIn" data-wow-duration="1s" data-wow-delay="1.5s" data-wow-offset="200">
                  <h2>Affiliations</h2><img src="{% static 'img/Optimized-Aff1.png' %}" alt="">
                </div>
              </div>
            </div>
          </div>
        </div>
      </footer>
      <div class="footer">
        <p>WashingtonNaturalGas &copy; All Rights Reserved.2021</p>
      </div>
      <!-- End Footer-->

templates/base/js.html
{% load static %}


<script src="{% static 'js/html5shiv.min.js' %}"></script>
<script src="{% static 'js/respond.min.js' %}"></script>

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/jquery.nicescroll.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script>new WOW().init();</script>
<script src="{% static 'js/main.js' %}"></script>

templates/base/navbar.html
{% load static %}

<div class="upper-barr">
    <div class="container">
      <div class="row">
        <div class="col-lg-5"></div>
        <div class="col-lg-7">
          <div class="row">
            <div class="col">
              <div class="icon"><i class="fab fa-facebook-f"></i><i class="fab fa-twitter"></i><i class="fab fa-google-plus-g"></i><i class="fab fa-linkedin-in"></i></div>
            </div>
            <div class="col"> 
              <div class="num"><i class="fas fa-phone-volume"> </i><span>(425) 355-3331</span></div>
            </div>
            <div class="col-lg-5">
              <div class="mail"><i class="far fa-envelope"></i><span>info@wanaturalgas.com</span></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container"><a href="/"><img src="{% static 'img/logo.jpg' %}" alt=""></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item {% if active == 'home' %}active{% endif %}"><a class="nav-link" href="{% url 'pages:home' %}">Home </a></li>
          <li class="nav-item {% if active == 'about' %}active{% endif %}"><a class="nav-link" href="{% url 'pages:about_us' %}">About</a></li>
          <li class="nav-item {% if active == 'heating' %}active{% endif %}"><a class="nav-link" href="{% url 'service:heating' %}">Heating</a></li>
          <li class="nav-item {% if active == 'cooling' %}active{% endif %}"><a class="nav-link" href="{% url 'service:cooling' %}">Cooling</a></li>
          <li class="nav-item {% if active == 'services' %}active{% endif %}"><a class="nav-link" href="{% url 'pages:services' %}">Services</a></li>
          <li class="nav-item {% if active == 'residential' %}active{% endif %}"><a class="nav-link" href="{% url 'pages:residential' %}">Residential</a></li>
          <li class="nav-item {% if active == 'financing' %}active{% endif %}"><a class="nav-link" href="{% url 'pages:financing' %}">Financing</a></li>
          <li class="nav-item {% if active == 'contact' %}active{% endif %}"><a class="nav-link" href="{% url 'receives:contact_us' %}">Contact</a></li>
          <li class="nav-item hidden-li">
            <div class="icon"><i class="fab fa-facebook-f"></i><i class="fab fa-twitter"></i><i class="fab fa-google-plus-g"></i><i class="fab fa-linkedin-in"></i></div>
          </li>
          <li class="nav-item hidden-li">
            <div class="num"><i class="fas fa-phone-volume"> </i><span>(425) 355-3331</span></div>
          </li>
          <li class="nav-item hidden-li">
            <div class="mail"><i class="far fa-envelope"></i><span>info@wanaturalgas.com</span></div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/base/submit_request_button.html
<div class="ggo">
    <button class="forrmm"><a href="{% url 'receives:request' %}">Submit A Maintenance Request</a></button>
</div>